### ISSUE TITLE
Lab 4 issue

### ISSUE THREAD

**Issue by chrispinkney** [pyvelkov/DeadLinkage#14]
Hi,

If possible can I work on lab 4 using your program? I'd like to implement a feature that takes a file filled with links to ignore and ignores them when checking a file for links.

For example: `DeadLinkage.jar --ignore ignore-urls.txt index.html` will take the links from `ignore-urls.txt` and not check for those links in `index.html`.

**Comment by pyvelkov** [comment]
Hey chris,
That sounds awesome. Do your thing, my bald headed friend.

**Comment by chrispinkney** [comment]
:older_man:

**Comment by chrispinkney** [comment]
Closed in 3cc6f4954f8afed110cf59a51682e1a1cb2d38ce
