### ISSUE TITLE
The need to install chromedriver in order to see the version of your tool

### ISSUE THREAD

**Issue by bpan2** [pyvelkov/DeadLinkage#8]
Is it possible for me to run your jar file without installing chromedriver?

When I just want to see the version of your tool, the following is the output:
![DeadLinkage-image](https://user-images.githubusercontent.com/5376006/94326749-3644f700-ff74-11ea-8b58-bc055db2657b.png)

**Comment by pyvelkov** [comment]
Hey. No I run the chrome web driver with means to scrape data from the html. You also need chrome installed. I will probably be modifying the next release so you can run version and help without opening the chromedriver.exe

**Comment by bpan2** [comment]
Hi. Thank for your quick reply. It's very professional.

Your usage of web drivers reminds me of web-scraping. If we use java to check status code of a link, it might allow us to skip jumping through hoops of 2-factor authentications.

**Comment by pyvelkov** [comment]
Yeah as i said it is my 0.1 release. The whole point of the use of chrome web driver is to incorporate the use of the selenium framework. Otherwise the dependency is not needed and can be done purely with java alone.

**Comment by bpan2** [comment]
You explain everything. Thank you. Have a nice weekend.
