### ISSUE TITLE
Lab 2 - Request for optional features

### ISSUE THREAD

**Issue by chrispinkney** [pyvelkov/DeadLinkage#9]
Hi again,

For Lab 2 would it be okay to do the following:
- Linux Support for command line arguments
    - Given this feature's small implementation time cost I'd like to propose doing a second one in addition:
- Error 30x Link redirection

Let me know!
Thanks

**Comment by pyvelkov** [comment]
Hey Chris,
That would be amazing. I was having trouble with the status 30x in my release 0.1 so I would appreciate the contribution.

Can't wait to see your solution.
Thanks,
Plamen
